services:
  mysql-cp:
    image: mysql:8
    container_name: mysql-cp
    environment:
      MYSQL_ROOT_PASSWORD: 030705
      MYSQL_DATABASE: cpdb
      MYSQL_USER: app
      MYSQL_PASSWORD: 030705
    command: >
      --performance-schema=OFF
      --innodb-buffer-pool-size=64M
      --max-connections=20
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  api-cp:
    build: .
    container_name: api-cp
    depends_on:
      - mysql-cp
    environment:
      DB_URL: jdbc:mysql://mysql-cp:3306/cpdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
      DB_USERNAME: app
      DB_PASSWORD: 030705
    ports:
      - "8080:8080"

volumes:
  mysql_data: